#!/bin/bash

SCRIPT_PATH="./src/main.mjs"

LINK_DEST="/usr/local/bin/bw"

echo "Running npm install..."
npm install

if [ $? -ne 0 ]; then
  echo "npm install failed. Exiting."
  exit 1
fi

if [ ! -f "$SCRIPT_PATH" ]; then
  echo "Error: $SCRIPT_PATH does not exist. Please provide the correct path to bw.mjs."
  exit 1
fi

chmod +x "$SCRIPT_PATH"

if [ -L "$LINK_DEST" ]; then
  echo "Symbolic link already exists at $LINK_DEST. Removing it first."
  sudo rm "$LINK_DEST"
fi

echo "Creating symbolic link for main.mjs..."
sudo ln -s "$(pwd)/$SCRIPT_PATH" "$LINK_DEST"

if [ -L "$LINK_DEST" ]; then
  echo "Symbolic link created successfully! You can now use the 'bw' command globally."
else
  echo "Error: Failed to create symbolic link."
fi
